namespace Sale.Application.Common.Context;

/// <summary>
///     Scoped context to pass transaction signature through the MediatR pipeline.
///     This allows Transaction SigningBehavior to inject signature WITHOUT HttpContext.
///     CLEAN ARCHITECTURE:
///     - Behavior (at layer boundary) reads from HttpContext
///     - Signature is stored in Application-level TransactionContext (scoped)
///     - Handler (pure application logic) injects TransactionContext - NOT HttpContext
///     - Application layer → Domain layer only
/// </summary>
public class TransactionContext
{
    /// <summary>
    ///     Digital signature hash generated by Security.API gRPC service
    /// </summary>
    public string? SignatureHash { get; set; }

    /// <summary>
    ///     Timestamp of signature generation (Unix milliseconds)
    /// </summary>
    public long? TimestampUtc { get; set; }

    /// <summary>
    ///     Operation type that was signed
    /// </summary>
    public string? OperationType { get; set; }

    /// <summary>
    ///     User ID that initiated the operation
    /// </summary>
    public string? UserId { get; set; }

    /// <summary>
    ///     Checks if transaction has valid signature
    /// </summary>
    public bool HasValidSignature => !string.IsNullOrWhiteSpace(SignatureHash);
}
