import '../entities/create_customer_params.dart';
import '../entities/customer.dart';
import '../entities/customer_list_result.dart';

abstract class CustomersRepository {
  Future<CustomerListResult> getCustomers({int page = 1, int pageSize = 20});

  /// Creates a new customer. Code is auto-generated by backend (e.g. cus-123-456).
  /// Throws [CustomerDuplicatePhoneException] if phone already exists.
  Future<Customer> createCustomer(CreateCustomerParams params);

  Future<Customer?> getCustomerById(String id);

  /// Throws [CustomerDuplicatePhoneException] if new phone already exists for another customer.
  Future<Customer> updateCustomer(String id, CreateCustomerParams params);

  Future<void> deleteCustomer(String id);
}
