import '../entities/create_customer_params.dart';
import '../entities/customer.dart';

abstract class CustomersRepository {
  Future<List<Customer>> getCustomers({int page = 1, int pageSize = 20});

  /// Creates a new customer. Code is auto-generated by backend (e.g. cus-123-456).
  /// Throws [CustomerDuplicatePhoneException] if phone already exists.
  Future<Customer> createCustomer(CreateCustomerParams params);
}
