/// Parameters for creating a new customer. Code is generated by backend.
class CreateCustomerParams {
  const CreateCustomerParams({
    required this.name,
    required this.address,
    required this.phone,
  });

  final String name;
  final String address;
  final String phone;
}
