using Sale.Domain.Identifiers;

namespace Sale.Application.Common.DTOs;

/// <summary>
///     DTO representing a customer digital signature for non-repudiation.
///     Ensures that customer creation operations can be verified to have been
///     performed by a specific user, providing accountability and non-repudiation.
/// </summary>
public sealed class CustomerSignatureDto
{
    /// <summary>
    ///     Unique identifier for this signature record.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    ///     The customer ID associated with this signature.
    /// </summary>
    public CustomerId CustomerId { get; set; }

    /// <summary>
    ///     The base64-encoded digital signature generated by Vault Transit Engine.
    /// </summary>
    public string Signature { get; set; } = null!;

    /// <summary>
    ///     The base64-encoded payload that was signed (for audit trail and verification).
    ///     Contains customer data and the user who created the customer.
    /// </summary>
    public string SignedPayload { get; set; } = null!;

    /// <summary>
    ///     The user ID of the person who created the customer (for non-repudiation).
    /// </summary>
    public UserId CreatedByUserId { get; set; }

    /// <summary>
    ///     The timestamp when the signature was created.
    /// </summary>
    public DateTime SignedAt { get; set; }

    /// <summary>
    ///     Indicates whether this signature has been verified against the stored data.
    /// </summary>
    public bool IsVerified { get; set; }
}

/// <summary>
///     Payload structure for customer creation signing.
///     This is what gets serialized to JSON, then base64-encoded, and signed by Vault.
/// </summary>
public sealed record CreateCustomerSignaturePayload(
    /// <summary>The customer's ID being created.</summary>
    string CustomerId,
    /// <summary>The customer's first name.</summary>
    string FirstName,
    /// <summary>The customer's last name.</summary>
    string LastName,
    /// <summary>The customer's address.</summary>
    string Address,
    /// <summary>The customer's phone number.</summary>
    string PhoneNumber,
    /// <summary>The ID of the user creating the customer (for non-repudiation).</summary>
    string CreatedByUserId,
    /// <summary>The timestamp when the signature operation occurs.</summary>
    DateTime SignedAt);
