using Sale.Domain.Abstractions;
using Sale.Domain.Identifiers;
using Sale.Domain.Identifiers.Id;

namespace Sale.Domain.Entities;

/// <summary>
///     CustomerSignature entity representing a digital signature for a customer creation operation.
///     Implements non-repudiation by storing:
///     - The customer being created
///     - The signature generated by Vault
///     - The user who created the customer
///     - The timestamp of the signature operation
///     This ensures accountability and allows verification that a specific user created a customer at a specific time.
/// </summary>
public sealed class CustomerSignature : BaseEntity<CustomerSignatureId>
{
    public CustomerSignature()
    {
        Id = CustomerSignatureId.New();
    }

    /// <summary>
    ///     The ID of the customer associated with this signature.
    /// </summary>
    public CustomerId CustomerId { get; set; }

    /// <summary>
    ///     The digital signature generated by Vault Transit Engine.
    ///     Format: vault:v1:{base64-encoded-signature}
    /// </summary>
    public string Signature { get; set; } = null!;

    /// <summary>
    ///     The base64-encoded payload that was signed.
    ///     Contains customer information and the user who created it.
    ///     Stored for audit trail and verification purposes.
    /// </summary>
    public string SignedPayload { get; set; } = null!;

    /// <summary>
    ///     The ID of the user who created the customer (tracked for non-repudiation).
    /// </summary>
    public UserId SignedByUserId { get; set; }

    /// <summary>
    ///     The exact timestamp when the signature was created.
    /// </summary>
    public DateTime SignedAt { get; set; }

    /// <summary>
    ///     Indicates whether this signature has been verified against the Vault Transit Engine.
    /// </summary>
    public bool IsVerified { get; set; }

    /// <summary>
    ///     The timestamp of the last verification operation, if any.
    /// </summary>
    public DateTime? VerifiedAt { get; set; }

    /// <summary>
    ///     Navigation property to the associated customer.
    /// </summary>
    public Customer? Customer { get; set; }
}
