export * from './approval.service';
import { ApprovalService } from './approval.service';
export * from './approvalAPI.service';
import { ApprovalAPIService } from './approvalAPI.service';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './identityAPI.service';
import { IdentityAPIService } from './identityAPI.service';
export * from './inventory.service';
import { InventoryService } from './inventory.service';
export * from './inventoryAPI.service';
import { InventoryAPIService } from './inventoryAPI.service';
export * from './manufacture.service';
import { ManufactureService } from './manufacture.service';
export * from './manufactureAPI.service';
import { ManufactureAPIService } from './manufactureAPI.service';
export * from './payroll.service';
import { PayrollService } from './payroll.service';
export * from './payrollAPI.service';
import { PayrollAPIService } from './payrollAPI.service';
export * from './sale.service';
import { SaleService } from './sale.service';
export * from './saleAPI.service';
import { SaleAPIService } from './saleAPI.service';
export const APIS = [ApprovalService, ApprovalAPIService, IdentityService, IdentityAPIService, InventoryService, InventoryAPIService, ManufactureService, ManufactureAPIService, PayrollService, PayrollAPIService, SaleService, SaleAPIService];
